name: CI Pipeline  # Optional name for your workflow

on:
  push:  # Trigger when code is pushed
    branches:
      - main
  pull_request:  # Trigger on pull requests
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Define the runner environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Fetch the latest code

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Specify Python version

      - name: Install dependencies
        run: pip install -r requirements.txt  

      - name: Run tests
        run: pytest  # Run tests (adjust according to your project)
